
-- Empty the old services table to insert the new ones exactly as requested
TRUNCATE TABLE `services`;

INSERT INTO `services` (`id`, `title`, `description`, `icon`, `price_inr`, `price_usd`) VALUES
(1, 'Web Development', 'High-quality, fast, and responsive website development for all types of businesses.', 'fa-laptop-code', 2500.00, 49.00),
(2, 'App Development', 'Native and cross-platform mobile apps for Android and iOS devices.', 'fa-mobile-alt', 2500.00, 49.00),
(3, 'Web + App (Both)', 'Complete package including both Web and Mobile application development.', 'fa-layer-group', 4000.00, 79.00),
(4, 'Frontend Only', 'Pixel-perfect, modern UI/UX development using React, Vue, or HTML/CSS/JS.', 'fa-paint-brush', 999.00, 19.00),
(5, 'Backend & APIs', 'Robust server-side development, database architecture, and REST/GraphQL APIs.', 'fa-server', 1499.00, 29.00),
(6, 'Maintenance & Support', 'Hourly maintenance for servers, bugs, speed optimization, and regular updates.', 'fa-tools', 500.00, 10.00);


-- Empty old portfolio
TRUNCATE TABLE `portfolio`;

INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('HealthGlobal', 'A powerful AI & Machine Learning platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'AI & Machine Learning', 'https://source.unsplash.com/random/400x300/?technology,software,1', 'https://demo.techelevatex.in/healthglobal-1');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('MedElite', 'A powerful Social Media App platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Social Media App', 'https://source.unsplash.com/random/400x300/?technology,software,2', 'https://demo.techelevatex.in/medelite-2');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('MegaMart X', 'A powerful E-Commerce platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'E-Commerce', 'https://source.unsplash.com/random/400x300/?technology,software,3', 'https://demo.techelevatex.in/megamart-x-3');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('CareX Portal', 'A powerful Healthcare platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Healthcare', 'https://source.unsplash.com/random/400x300/?technology,software,4', 'https://demo.techelevatex.in/carex-portal-4');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('PropertySystem', 'A powerful ERP System platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'ERP System', 'https://source.unsplash.com/random/400x300/?technology,software,5', 'https://demo.techelevatex.in/propertysystem-5');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('MedApp', 'A powerful ERP System platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'ERP System', 'https://source.unsplash.com/random/400x300/?technology,software,6', 'https://demo.techelevatex.in/medapp-6');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('MegaMart Prime', 'A powerful E-Commerce platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'E-Commerce', 'https://source.unsplash.com/random/400x300/?technology,software,7', 'https://demo.techelevatex.in/megamart-prime-7');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('PropertyPlus', 'A powerful Logistics platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Logistics', 'https://source.unsplash.com/random/400x300/?technology,software,8', 'https://demo.techelevatex.in/propertyplus-8');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('CareElite Portal', 'A powerful Healthcare platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Healthcare', 'https://source.unsplash.com/random/400x300/?technology,software,9', 'https://demo.techelevatex.in/careelite-portal-9');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('PayApp', 'A powerful Social Media App platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Social Media App', 'https://source.unsplash.com/random/400x300/?technology,software,10', 'https://demo.techelevatex.in/payapp-10');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('ShipSolutions', 'A powerful ERP System platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'ERP System', 'https://source.unsplash.com/random/400x300/?technology,software,11', 'https://demo.techelevatex.in/shipsolutions-11');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('PaySolutions', 'A powerful Logistics platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Logistics', 'https://source.unsplash.com/random/400x300/?technology,software,12', 'https://demo.techelevatex.in/paysolutions-12');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('LearnSolutions LMS', 'A powerful EdTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'EdTech', 'https://source.unsplash.com/random/400x300/?technology,software,13', 'https://demo.techelevatex.in/learnsolutions-lms-13');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('CRMApp', 'A powerful ERP System platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'ERP System', 'https://source.unsplash.com/random/400x300/?technology,software,14', 'https://demo.techelevatex.in/crmapp-14');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('HealthHub', 'A powerful SaaS CRM platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'SaaS CRM', 'https://source.unsplash.com/random/400x300/?technology,software,15', 'https://demo.techelevatex.in/healthhub-15');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('FoodCloud', 'A powerful SaaS CRM platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'SaaS CRM', 'https://source.unsplash.com/random/400x300/?technology,software,16', 'https://demo.techelevatex.in/foodcloud-16');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('LearnPortal LMS', 'A powerful EdTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'EdTech', 'https://source.unsplash.com/random/400x300/?technology,software,17', 'https://demo.techelevatex.in/learnportal-lms-17');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('LearnConnect LMS', 'A powerful EdTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'EdTech', 'https://source.unsplash.com/random/400x300/?technology,software,18', 'https://demo.techelevatex.in/learnconnect-lms-18');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('FinSystem', 'A powerful Social Media App platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Social Media App', 'https://source.unsplash.com/random/400x300/?technology,software,19', 'https://demo.techelevatex.in/finsystem-19');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('FinSolutions', 'A powerful Real Estate platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Real Estate', 'https://source.unsplash.com/random/400x300/?technology,software,20', 'https://demo.techelevatex.in/finsolutions-20');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('CarePortal Portal', 'A powerful Healthcare platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Healthcare', 'https://source.unsplash.com/random/400x300/?technology,software,21', 'https://demo.techelevatex.in/careportal-portal-21');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('FoodPlus', 'A powerful ERP System platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'ERP System', 'https://source.unsplash.com/random/400x300/?technology,software,22', 'https://demo.techelevatex.in/foodplus-22');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('ShopSolutions', 'A powerful Logistics platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Logistics', 'https://source.unsplash.com/random/400x300/?technology,software,23', 'https://demo.techelevatex.in/shopsolutions-23');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('PaySystem', 'A powerful ERP System platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'ERP System', 'https://source.unsplash.com/random/400x300/?technology,software,24', 'https://demo.techelevatex.in/paysystem-24');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('FinSystem', 'A powerful Logistics platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Logistics', 'https://source.unsplash.com/random/400x300/?technology,software,25', 'https://demo.techelevatex.in/finsystem-25');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('HealthHub', 'A powerful AI & Machine Learning platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'AI & Machine Learning', 'https://source.unsplash.com/random/400x300/?technology,software,26', 'https://demo.techelevatex.in/healthhub-26');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('FinElite', 'A powerful FinTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'FinTech', 'https://source.unsplash.com/random/400x300/?technology,software,27', 'https://demo.techelevatex.in/finelite-27');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('HealthSolutions', 'A powerful SaaS CRM platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'SaaS CRM', 'https://source.unsplash.com/random/400x300/?technology,software,28', 'https://demo.techelevatex.in/healthsolutions-28');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('ShopSmart', 'A powerful AI & Machine Learning platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'AI & Machine Learning', 'https://source.unsplash.com/random/400x300/?technology,software,29', 'https://demo.techelevatex.in/shopsmart-29');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('FinApp', 'A powerful Logistics platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Logistics', 'https://source.unsplash.com/random/400x300/?technology,software,30', 'https://demo.techelevatex.in/finapp-30');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('CareNetwork Portal', 'A powerful Healthcare platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Healthcare', 'https://source.unsplash.com/random/400x300/?technology,software,31', 'https://demo.techelevatex.in/carenetwork-portal-31');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('LearnSolutions LMS', 'A powerful EdTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'EdTech', 'https://source.unsplash.com/random/400x300/?technology,software,32', 'https://demo.techelevatex.in/learnsolutions-lms-32');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('ShopPortal', 'A powerful ERP System platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'ERP System', 'https://source.unsplash.com/random/400x300/?technology,software,33', 'https://demo.techelevatex.in/shopportal-33');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('MegaMart Connect', 'A powerful E-Commerce platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'E-Commerce', 'https://source.unsplash.com/random/400x300/?technology,software,34', 'https://demo.techelevatex.in/megamart-connect-34');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('ShipApp', 'A powerful ERP System platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'ERP System', 'https://source.unsplash.com/random/400x300/?technology,software,35', 'https://demo.techelevatex.in/shipapp-35');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('MedPrime', 'A powerful FinTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'FinTech', 'https://source.unsplash.com/random/400x300/?technology,software,36', 'https://demo.techelevatex.in/medprime-36');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('ShipPrime', 'A powerful Real Estate platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Real Estate', 'https://source.unsplash.com/random/400x300/?technology,software,37', 'https://demo.techelevatex.in/shipprime-37');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('EduHub', 'A powerful SaaS CRM platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'SaaS CRM', 'https://source.unsplash.com/random/400x300/?technology,software,38', 'https://demo.techelevatex.in/eduhub-38');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('MegaMart X', 'A powerful E-Commerce platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'E-Commerce', 'https://source.unsplash.com/random/400x300/?technology,software,39', 'https://demo.techelevatex.in/megamart-x-39');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('MedSolutions', 'A powerful FinTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'FinTech', 'https://source.unsplash.com/random/400x300/?technology,software,40', 'https://demo.techelevatex.in/medsolutions-40');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('LearnApp LMS', 'A powerful EdTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'EdTech', 'https://source.unsplash.com/random/400x300/?technology,software,41', 'https://demo.techelevatex.in/learnapp-lms-41');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('CarePortal Portal', 'A powerful Healthcare platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Healthcare', 'https://source.unsplash.com/random/400x300/?technology,software,42', 'https://demo.techelevatex.in/careportal-portal-42');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('MegaMart System', 'A powerful E-Commerce platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'E-Commerce', 'https://source.unsplash.com/random/400x300/?technology,software,43', 'https://demo.techelevatex.in/megamart-system-43');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('ShipPortal', 'A powerful Real Estate platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Real Estate', 'https://source.unsplash.com/random/400x300/?technology,software,44', 'https://demo.techelevatex.in/shipportal-44');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('EduApp', 'A powerful FinTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'FinTech', 'https://source.unsplash.com/random/400x300/?technology,software,45', 'https://demo.techelevatex.in/eduapp-45');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('AutoConnect', 'A powerful Real Estate platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Real Estate', 'https://source.unsplash.com/random/400x300/?technology,software,46', 'https://demo.techelevatex.in/autoconnect-46');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('FinConnect', 'A powerful ERP System platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'ERP System', 'https://source.unsplash.com/random/400x300/?technology,software,47', 'https://demo.techelevatex.in/finconnect-47');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('ShopNetwork', 'A powerful Logistics platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Logistics', 'https://source.unsplash.com/random/400x300/?technology,software,48', 'https://demo.techelevatex.in/shopnetwork-48');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('HealthApp', 'A powerful AI & Machine Learning platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'AI & Machine Learning', 'https://source.unsplash.com/random/400x300/?technology,software,49', 'https://demo.techelevatex.in/healthapp-49');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('LearnNetwork LMS', 'A powerful EdTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'EdTech', 'https://source.unsplash.com/random/400x300/?technology,software,50', 'https://demo.techelevatex.in/learnnetwork-lms-50');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('EduSystem', 'A powerful ERP System platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'ERP System', 'https://source.unsplash.com/random/400x300/?technology,software,51', 'https://demo.techelevatex.in/edusystem-51');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('PropertyPrime', 'A powerful Social Media App platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Social Media App', 'https://source.unsplash.com/random/400x300/?technology,software,52', 'https://demo.techelevatex.in/propertyprime-52');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('FoodConnect', 'A powerful Social Media App platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Social Media App', 'https://source.unsplash.com/random/400x300/?technology,software,53', 'https://demo.techelevatex.in/foodconnect-53');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('PaySolutions', 'A powerful Real Estate platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Real Estate', 'https://source.unsplash.com/random/400x300/?technology,software,54', 'https://demo.techelevatex.in/paysolutions-54');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('AutoConnect', 'A powerful FinTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'FinTech', 'https://source.unsplash.com/random/400x300/?technology,software,55', 'https://demo.techelevatex.in/autoconnect-55');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('HealthPortal', 'A powerful Social Media App platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Social Media App', 'https://source.unsplash.com/random/400x300/?technology,software,56', 'https://demo.techelevatex.in/healthportal-56');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('FoodApp', 'A powerful Real Estate platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Real Estate', 'https://source.unsplash.com/random/400x300/?technology,software,57', 'https://demo.techelevatex.in/foodapp-57');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('LearnPortal LMS', 'A powerful EdTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'EdTech', 'https://source.unsplash.com/random/400x300/?technology,software,58', 'https://demo.techelevatex.in/learnportal-lms-58');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('HealthSolutions', 'A powerful AI & Machine Learning platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'AI & Machine Learning', 'https://source.unsplash.com/random/400x300/?technology,software,59', 'https://demo.techelevatex.in/healthsolutions-59');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('AutoPrime', 'A powerful Real Estate platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Real Estate', 'https://source.unsplash.com/random/400x300/?technology,software,60', 'https://demo.techelevatex.in/autoprime-60');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('EduHub', 'A powerful FinTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'FinTech', 'https://source.unsplash.com/random/400x300/?technology,software,61', 'https://demo.techelevatex.in/eduhub-61');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('CRMElite', 'A powerful ERP System platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'ERP System', 'https://source.unsplash.com/random/400x300/?technology,software,62', 'https://demo.techelevatex.in/crmelite-62');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('HealthNetwork', 'A powerful ERP System platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'ERP System', 'https://source.unsplash.com/random/400x300/?technology,software,63', 'https://demo.techelevatex.in/healthnetwork-63');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('PropertyCloud', 'A powerful SaaS CRM platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'SaaS CRM', 'https://source.unsplash.com/random/400x300/?technology,software,64', 'https://demo.techelevatex.in/propertycloud-64');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('MegaMart Solutions', 'A powerful E-Commerce platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'E-Commerce', 'https://source.unsplash.com/random/400x300/?technology,software,65', 'https://demo.techelevatex.in/megamart-solutions-65');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('PayGlobal', 'A powerful SaaS CRM platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'SaaS CRM', 'https://source.unsplash.com/random/400x300/?technology,software,66', 'https://demo.techelevatex.in/payglobal-66');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('ShipConnect', 'A powerful SaaS CRM platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'SaaS CRM', 'https://source.unsplash.com/random/400x300/?technology,software,67', 'https://demo.techelevatex.in/shipconnect-67');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('CRMPro', 'A powerful Social Media App platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Social Media App', 'https://source.unsplash.com/random/400x300/?technology,software,68', 'https://demo.techelevatex.in/crmpro-68');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('ShopPro', 'A powerful ERP System platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'ERP System', 'https://source.unsplash.com/random/400x300/?technology,software,69', 'https://demo.techelevatex.in/shoppro-69');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('PropertySmart', 'A powerful FinTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'FinTech', 'https://source.unsplash.com/random/400x300/?technology,software,70', 'https://demo.techelevatex.in/propertysmart-70');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('FoodSolutions', 'A powerful Real Estate platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Real Estate', 'https://source.unsplash.com/random/400x300/?technology,software,71', 'https://demo.techelevatex.in/foodsolutions-71');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('ShipSmart', 'A powerful AI & Machine Learning platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'AI & Machine Learning', 'https://source.unsplash.com/random/400x300/?technology,software,72', 'https://demo.techelevatex.in/shipsmart-72');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('MegaMart Smart', 'A powerful E-Commerce platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'E-Commerce', 'https://source.unsplash.com/random/400x300/?technology,software,73', 'https://demo.techelevatex.in/megamart-smart-73');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('EduSolutions', 'A powerful AI & Machine Learning platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'AI & Machine Learning', 'https://source.unsplash.com/random/400x300/?technology,software,74', 'https://demo.techelevatex.in/edusolutions-74');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('PropertyConnect', 'A powerful Social Media App platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Social Media App', 'https://source.unsplash.com/random/400x300/?technology,software,75', 'https://demo.techelevatex.in/propertyconnect-75');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('HealthPrime', 'A powerful Social Media App platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Social Media App', 'https://source.unsplash.com/random/400x300/?technology,software,76', 'https://demo.techelevatex.in/healthprime-76');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('MegaMart Smart', 'A powerful E-Commerce platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'E-Commerce', 'https://source.unsplash.com/random/400x300/?technology,software,77', 'https://demo.techelevatex.in/megamart-smart-77');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('PayHub', 'A powerful Logistics platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Logistics', 'https://source.unsplash.com/random/400x300/?technology,software,78', 'https://demo.techelevatex.in/payhub-78');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('MegaMart Prime', 'A powerful E-Commerce platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'E-Commerce', 'https://source.unsplash.com/random/400x300/?technology,software,79', 'https://demo.techelevatex.in/megamart-prime-79');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('LearnConnect LMS', 'A powerful EdTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'EdTech', 'https://source.unsplash.com/random/400x300/?technology,software,80', 'https://demo.techelevatex.in/learnconnect-lms-80');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('FinHub', 'A powerful Social Media App platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Social Media App', 'https://source.unsplash.com/random/400x300/?technology,software,81', 'https://demo.techelevatex.in/finhub-81');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('FoodPro', 'A powerful SaaS CRM platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'SaaS CRM', 'https://source.unsplash.com/random/400x300/?technology,software,82', 'https://demo.techelevatex.in/foodpro-82');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('PropertySolutions', 'A powerful AI & Machine Learning platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'AI & Machine Learning', 'https://source.unsplash.com/random/400x300/?technology,software,83', 'https://demo.techelevatex.in/propertysolutions-83');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('CarePortal Portal', 'A powerful Healthcare platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Healthcare', 'https://source.unsplash.com/random/400x300/?technology,software,84', 'https://demo.techelevatex.in/careportal-portal-84');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('CarePortal Portal', 'A powerful Healthcare platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Healthcare', 'https://source.unsplash.com/random/400x300/?technology,software,85', 'https://demo.techelevatex.in/careportal-portal-85');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('EduConnect', 'A powerful ERP System platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'ERP System', 'https://source.unsplash.com/random/400x300/?technology,software,86', 'https://demo.techelevatex.in/educonnect-86');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('MegaMart Elite', 'A powerful E-Commerce platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'E-Commerce', 'https://source.unsplash.com/random/400x300/?technology,software,87', 'https://demo.techelevatex.in/megamart-elite-87');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('CareNetwork Portal', 'A powerful Healthcare platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Healthcare', 'https://source.unsplash.com/random/400x300/?technology,software,88', 'https://demo.techelevatex.in/carenetwork-portal-88');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('FoodPrime', 'A powerful Real Estate platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Real Estate', 'https://source.unsplash.com/random/400x300/?technology,software,89', 'https://demo.techelevatex.in/foodprime-89');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('FinSmart', 'A powerful Social Media App platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Social Media App', 'https://source.unsplash.com/random/400x300/?technology,software,90', 'https://demo.techelevatex.in/finsmart-90');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('CRMX', 'A powerful Social Media App platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Social Media App', 'https://source.unsplash.com/random/400x300/?technology,software,91', 'https://demo.techelevatex.in/crmx-91');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('AutoHub', 'A powerful SaaS CRM platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'SaaS CRM', 'https://source.unsplash.com/random/400x300/?technology,software,92', 'https://demo.techelevatex.in/autohub-92');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('CarePlus Portal', 'A powerful Healthcare platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Healthcare', 'https://source.unsplash.com/random/400x300/?technology,software,93', 'https://demo.techelevatex.in/careplus-portal-93');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('ShipSystem', 'A powerful Social Media App platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Social Media App', 'https://source.unsplash.com/random/400x300/?technology,software,94', 'https://demo.techelevatex.in/shipsystem-94');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('PropertyX', 'A powerful FinTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'FinTech', 'https://source.unsplash.com/random/400x300/?technology,software,95', 'https://demo.techelevatex.in/propertyx-95');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('ShipPlus', 'A powerful FinTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'FinTech', 'https://source.unsplash.com/random/400x300/?technology,software,96', 'https://demo.techelevatex.in/shipplus-96');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('LearnPortal LMS', 'A powerful EdTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'EdTech', 'https://source.unsplash.com/random/400x300/?technology,software,97', 'https://demo.techelevatex.in/learnportal-lms-97');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('ShipX', 'A powerful SaaS CRM platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'SaaS CRM', 'https://source.unsplash.com/random/400x300/?technology,software,98', 'https://demo.techelevatex.in/shipx-98');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('CRMConnect', 'A powerful Logistics platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Logistics', 'https://source.unsplash.com/random/400x300/?technology,software,99', 'https://demo.techelevatex.in/crmconnect-99');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('AutoGlobal', 'A powerful AI & Machine Learning platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'AI & Machine Learning', 'https://source.unsplash.com/random/400x300/?technology,software,100', 'https://demo.techelevatex.in/autoglobal-100');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('CRMSystem', 'A powerful AI & Machine Learning platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'AI & Machine Learning', 'https://source.unsplash.com/random/400x300/?technology,software,101', 'https://demo.techelevatex.in/crmsystem-101');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('LearnSystem LMS', 'A powerful EdTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'EdTech', 'https://source.unsplash.com/random/400x300/?technology,software,102', 'https://demo.techelevatex.in/learnsystem-lms-102');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('HealthPro', 'A powerful SaaS CRM platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'SaaS CRM', 'https://source.unsplash.com/random/400x300/?technology,software,103', 'https://demo.techelevatex.in/healthpro-103');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('ShopPrime', 'A powerful Real Estate platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Real Estate', 'https://source.unsplash.com/random/400x300/?technology,software,104', 'https://demo.techelevatex.in/shopprime-104');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('AutoPro', 'A powerful FinTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'FinTech', 'https://source.unsplash.com/random/400x300/?technology,software,105', 'https://demo.techelevatex.in/autopro-105');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('MegaMart Connect', 'A powerful E-Commerce platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'E-Commerce', 'https://source.unsplash.com/random/400x300/?technology,software,106', 'https://demo.techelevatex.in/megamart-connect-106');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('MegaMart X', 'A powerful E-Commerce platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'E-Commerce', 'https://source.unsplash.com/random/400x300/?technology,software,107', 'https://demo.techelevatex.in/megamart-x-107');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('MedSmart', 'A powerful Social Media App platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Social Media App', 'https://source.unsplash.com/random/400x300/?technology,software,108', 'https://demo.techelevatex.in/medsmart-108');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('FoodSmart', 'A powerful Social Media App platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Social Media App', 'https://source.unsplash.com/random/400x300/?technology,software,109', 'https://demo.techelevatex.in/foodsmart-109');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('ShopSmart', 'A powerful SaaS CRM platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'SaaS CRM', 'https://source.unsplash.com/random/400x300/?technology,software,110', 'https://demo.techelevatex.in/shopsmart-110');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('AutoGlobal', 'A powerful FinTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'FinTech', 'https://source.unsplash.com/random/400x300/?technology,software,111', 'https://demo.techelevatex.in/autoglobal-111');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('HealthConnect', 'A powerful Logistics platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Logistics', 'https://source.unsplash.com/random/400x300/?technology,software,112', 'https://demo.techelevatex.in/healthconnect-112');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('FoodNetwork', 'A powerful Real Estate platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Real Estate', 'https://source.unsplash.com/random/400x300/?technology,software,113', 'https://demo.techelevatex.in/foodnetwork-113');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('PropertyGlobal', 'A powerful AI & Machine Learning platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'AI & Machine Learning', 'https://source.unsplash.com/random/400x300/?technology,software,114', 'https://demo.techelevatex.in/propertyglobal-114');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('CRMHub', 'A powerful AI & Machine Learning platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'AI & Machine Learning', 'https://source.unsplash.com/random/400x300/?technology,software,115', 'https://demo.techelevatex.in/crmhub-115');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('ShopConnect', 'A powerful AI & Machine Learning platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'AI & Machine Learning', 'https://source.unsplash.com/random/400x300/?technology,software,116', 'https://demo.techelevatex.in/shopconnect-116');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('LearnSmart LMS', 'A powerful EdTech platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'EdTech', 'https://source.unsplash.com/random/400x300/?technology,software,117', 'https://demo.techelevatex.in/learnsmart-lms-117');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('PropertySmart', 'A powerful Logistics platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'Logistics', 'https://source.unsplash.com/random/400x300/?technology,software,118', 'https://demo.techelevatex.in/propertysmart-118');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('MegaMart Plus', 'A powerful E-Commerce platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'E-Commerce', 'https://source.unsplash.com/random/400x300/?technology,software,119', 'https://demo.techelevatex.in/megamart-plus-119');
INSERT INTO `portfolio` (`title`, `description`, `category`, `image_url`, `demo_url`) VALUES ('PayGlobal', 'A powerful ERP System platform designed for high performance, scalability, and seamless user experience. Includes modern dashboards, secure databases, and real-time APIs.', 'ERP System', 'https://source.unsplash.com/random/400x300/?technology,software,120', 'https://demo.techelevatex.in/payglobal-120');
